paths:
  /notes:
    post:
      summary: Create a new note
      tags:
        - Notes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                memo_date:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        201:
          description: Note created successfully
    
    get:
      summary: Retrieve all notes for current user
      tags: [Notes]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: items_per_page
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Successfully retrieved notes list

  /notes/{id}:
    get:
      summary: Retrieve a single note by ID
      tags: [Notes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved note
        404:
          description: Note not found
    
    put:
      summary: Update a note
      tags: [Notes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 64
                content:
                  type: string
                  minLength: 1
                memo_date:
                  type: string
                  minLength: 8
                  maxLength: 8
                tags:
                  type: array
                  items:
                    type: string
      responses:
        200:
          description: Note updated successfully
    
    delete:
      summary: Delete a note
      tags: [Notes]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        204:
          description: Note deleted successfully
        404:
          description: Note not found